package com.stafsus.api.constant

class MessageKey {
	companion object {
		const val USER_NOT_FOUND = "user.not_found"
		const val PRODUCT_NOT_FOUND = "product.not_found"
		const val CHANNEL_NOT_FOUND = "channel.not_found"
		const val CHANNEL_WITH_ID_NOT_FOUND = "channel.id.not_found"
		const val PRICE_NOT_FOUND = "price.not_found"
		const val INDUSTRY_NOT_FOUND = "industry.not_found"
		const val COMPANY_NOT_FOUND = "company.not_found"
		const val API_KEY_NOT_FOUND = "api.key.not_found"
		const val TRANSACTION_NOT_FOUND = "transaction.not_found"
		const val STAFF_NOT_FOUND = "staff.not_found"
		const val TELEGRAM_TOKEN_REQUIRED = "telegram.token.required"
		const val INVALID_USER_TO_VERIFY_STAFF = "invalid.user.to.verify.staff"
		const val SYNC_CONTACT_FAILED = "sync.contact.failed"
		const val UNEXPECTED_EXCEPTION = "unexpected.exception"
		const val SYNC_CHAT_FAILED = "sync.chat.failed"
		const val PRICE_MUST_GREATER_THAN_ZERO = "price.greater_than_zero"
		const val INVALID_VERSION = "invalid.version"
		const val INVALID_SIGNATURE_KEY = "invalid.signature_key"
		const val DELETE_DEPARTMENT_SUCCESS = "department.delete.success"
		const val DEPARTMENT_NOT_FOUND = "department.not.found"
		const val TAG_NOT_FOUND = "tag.not.found"
		const val INVALID_EMAIL_OR_PASSWORD = "invalid.email.or.password"
		const val OLD_PASSWORD_NOT_MATCHED = "old.password.not.matched"
		const val UNAUTHORIZED_ERROR = "unauthorized.error"
		const val EMAIL_EXISTS = "email.exists"
		const val STAFF_EXISTS = "staff.exists"
		const val INVALID_REFRESH_TOKEN = "invalid.refresh.token"
		const val TRIAL_TIME_IS_UP = "trial.time.is.up"
		const val MAXIMUM_CHANNEL_HAS_BEEN_REACHED = "maximum.channel.has.been.reached"
		const val ADMIN_ACCESS_DENIED = "admin.access.denied"
		const val COMPANY_REQUIRED = "company.required"
		const val AUTHORITY_INVALID = "authority.invalid"
		const val PRODUCT_TYPE_INVALID = "product_type.invalid"
	}
}