spring:
  rabbitmq:
    addresses: ${AMQP_ADDRESS:amqps://kxaihelk:p_vOwOpE5TEjqmXbjM7tg7Y35fpfeFs0@snake.rmq2.cloudamqp.com/kxaihelk}
    listener:
      concurrency: 5
      max-concurrency: 10
    dynamic: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wa}
    username: ${DB_USER:wa}
    password: ${DB_PASSWORD:wa123}
    driverClassName: org.postgresql.Driver

app:
  device:
    period: 3
  security:
    jwtSecret: stafus-api
    jwtExpirationInMs: 3600000
    refreshExpirationDateInMs: 604800000

springdoc:
  use-fqn: true
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    com.stafsus.waapi: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} Tracing: %X{tracingId}  [%t] %-5level %logger{36} - %msg %n"

feign:
  client:
    config:
      wa-device:
        url: http://localhost:8081
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic