spring:
  rabbitmq:
    addresses: ${AMQP_ADDRESS:amqp://guest:guest@localhost:5672}
    listener:
      concurrency: 5
      max-concurrency: 10
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2

    dynamic: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wa}
    username: ${DB_USER:wa}
    password: ${DB_PASSWORD:wa123}
    driverClassName: org.postgresql.Driver

app:
  device:
    period: 3
  security:
    jwtSecret: stafus-api
    jwtExpirationInMs: 3600000
    refreshExpirationDateInMs: 604800000

springdoc:
  use-fqn: true
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha

logging:
#  level:
#    ROOT: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} Tracing: %X{tracingId}  [%t] %-5level %logger{36} - %msg %n"

feign:
  client:
    config:
      wa-device:
        url: http://localhost:8081
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic