CREATE TABLE api_key
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    server_key text NOT NULL,
    secret_key text NOT NULL,
    client_key text  NOT NULL,
    user_id bigint,

    CONSTRAINT api_key_pkey PRIMARY KEY (id),

    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);
CREATE INDEX idx_api_key_user_id ON api_key(user_id);