CREATE TABLE refresh_token
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    expiry_date timestamp without time zone,
    token character varying(255) NOT NULL,
    user_id bigint,
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp without time zone,
    updated_by character varying(255),
    version bigint NOT NULL
);
CREATE INDEX idx_refresh_token_user_id ON refresh_token(user_id);