CREATE TABLE price
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(60) NOT NULL,
    price decimal(9,2) NOT NULL,
    access_time bigint NOT NULL,
    price_type character varying (30), -- subscribe, product
    agent_amount integer, -- will
    channel_amount integer,
    monthly_active_visitor integer,
    product_id bigint,
    CONSTRAINT price_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);

CREATE INDEX idx_price_product_id ON price(product_id);
