CREATE TABLE item_details
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(60) NOT NULL,
    merchant_name character varying(60),
    price_id bigint NOT NULL,
    quantity integer NOT NULL,
    order_id character varying(255) NOT NULL,
    CONSTRAINT item_details_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);

CREATE INDEX idx_item_details_product_id ON item_details(price_id);
CREATE INDEX idx_item_details_order_id ON item_details(order_id);
