CREATE TABLE quota(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    max_agent integer NOT NULL,
    max_channel integer NOT NULL,
    monthly_active_visitor integer,
    expired_at timestamp without time zone NOT NULL,
    CONSTRAINT quota_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
)