CREATE TABLE user_principal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(60) NOT NULL,
    business_name character varying(100)  NOT NULL,
    password character varying(60) NOT NULL,
    status character varying(20)  NOT NULL,
    parent_id bigint,
    quota_id bigint,
    CONSTRAINT user_principal_pkey PRIMARY KEY (id),

    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);