CREATE TABLE chat
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text,
    server character varying(20),
    serialized character varying(255),
    number character varying(255),
    picture text,
    archived boolean,
    is_group boolean,
    is_read_only boolean,
    pinned boolean,
    is_muted boolean,
    unread_count bigint,
    mute_expiration timestamp without time zone,
    "timestamp" timestamp without time zone,
    CONSTRAINT chat_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);
