CREATE TABLE message
(
    id character varying(255) NOT NULL,
    server character varying(255),
    "number" character varying(255),
    user_serialized character varying(255),
    serialized character varying(255),
    ack integer,
    from_user character varying(255),
    to_user character varying(255),
    body text,
    "timestamp" timestamp without time zone,
    device_type character varying(30),
    is_forwarded boolean,
    type character varying(30),
    forwarding_score integer,
    is_status boolean,
    is_starred boolean,
    broadcast boolean,
    from_me boolean,
    has_media boolean,
    has_quoted_msg boolean,
    location text,
    v_cards text,
    mentioned_ids text,
    links text,
    CONSTRAINT message_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);
