CREATE TABLE "participant"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    number character varying(255),
    server character varying(10),
    is_admin boolean,
    group_id character varying(255),
    CONSTRAINT participant_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL,
    UNIQUE (group_id, number)
);
