CREATE TABLE email_verification
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) NOT NULL,
    verification_code character varying(60) NOT NULL,
    expire_at timestamp without time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT email_verification_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);