CREATE TABLE telegram_channel(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bot_name character varying(225),
    bot_username character varying(255),
    bot_token text,
    status character varying(20) NOT NULL,
    device_status character varying(20) NOT NULL,
    channel_id bigint NOT NULL,
    CONSTRAINT telegram_channel_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);