CREATE TABLE contact
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    number character varying(20),
    name character varying(60),
    picture text,
    source character varying(30),
    is_group boolean,
    user_id bigint NOT NULL,
    CONSTRAINT contact_pkey PRIMARY KEY (number),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);

CREATE INDEX idx_contact_user_id ON contact(user_id);