CREATE TABLE product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(60) NOT NULL,
    image_url text NOT NULL,
    description_en text,
    description_id text,
    priority bigint NOT NULL,
    documentation_url text,
    type character varying(20),
    CONSTRAINT product_pkey PRIMARY KEY (id),
    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);