CREATE TABLE quick_reply
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    command character varying(60) NOT NULL,
    message text  NOT NULL,
    status character varying(15) NOT NULL,
    user_id bigint NOT NULL,

    CONSTRAINT quick_reply_pkey PRIMARY KEY (id),

    created_at timestamp without time zone NOT NULL,
    created_by character varying(255) ,
    updated_at timestamp without time zone,
    updated_by character varying(255) ,
    version bigint NOT NULL
);
CREATE INDEX idx_quick_reply_user_id ON quick_reply(user_id);